AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '*.gemspec'
    - '**/*.rb'
    - Gemfile
    - Rakefile
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-google-tag-manager.rb'
