require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - '*.gemspec'
    - '**/*.rb'
    - Gemfile
    - Rakefile
  Exclude:
    - bin/rake
    - bin/rubocop
    - bin/mutant
    - bin/rspec
    - 'vendor/**/*'

Lint/EmptyClass:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-google-tag-manager.rb'

Style/ClassVars:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
