AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '*.gemspec'
    - '**/*.rb'
    - Gemfile
    - Rakefile
  Exclude:
    - bin/rake
    - bin/rubocop
    - bin/mutant
    - bin/rspec
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-google-tag-manager.rb'

Style/ClassVars:
  Exclude:
    - 'lib/jekyll-google-tag-manager.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
