version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          JEKYLL_ENV: test
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout

      - run:
          name: Ruby version
          command: ruby --version

      - run:
          name: Install Bundler 2
          command: |
            sudo gem update --system
            sudo gem install bundler -f -v 2.0.2

      - run:
          name: Bundler version
          command: bundle --version

      - restore_cache:
          keys:
            - ruby-deps-v1-{{ checksum "jekyll-google-tag-manager.gemspec" }}
            - ruby-deps-v1-

      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install

      - save_cache:
          key: ruby-deps-v1-{{ checksum "jekyll-google-tag-manager.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: bin/rspec

      - run:
          name: Run mutation tests
          command: bin/rake mutation

      - run:
          name: Lint code
          command: bin/rubocop

      - run:
          name: Build gem
          command: bin/rake build

      - run:
          name: Inspect gem contents
          command: |
            cd pkg
            tar xf *.gem
            tar tvf data.tar.gz

      - store_artifacts:
          path: coverage
          prefix: coverage
