name: Test
on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    env:
      PARALLEL_PROCESSOR_COUNT: 2
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Ruby version
        run: ruby -v

      - name: Bundler environment
        run: bundle env

      - name: Run specs
        run: bin/rspec

      - name: Run mutation tests
        run: bin/rake mutation

      - name: Lint code
        run: bin/rubocop --parallel

      - name: Build gem
        run: bin/rake build

      - name: Inspect gem contents
        run: |
          cd pkg
          tar xf *.gem
          tar tvf data.tar.gz
